package com.Gritty.Linki.domain.kafka.chat.enums;

public enum EventType {
    PROPOSAL_CREATE,PROPOSAL_ACTIVE,PROPOSAL_MODIFY,PROPOSAL_REJECT,PROPOSAL_DELETE,
    CONTRACT_CREATE,CONTRACT_SIGN,CONTRACT_COMPLETED
}
