spring:
  application:
    name: admin-integration-service
  profiles:
    active: main
  config:
    import: optional:configserver:http://admin:1234@211.188.61.90:9000

  cloud:
    config:
      label: main