eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  config:
    import: "optional:application-secret.properties"
  jwt:
    secret: ${secret-HS256}

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 5000
      lettuce:
        pool:
          max-active: 10
          max-idle: 10
          min-idle: 2











