server:
  port: 8000

spring:
  application:
    name: apigateway-service

  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:3002"
            allowedMethods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true

      routes:
        - id: integration-client-service
          uri: lb://INTEGRATION-SERVICE
          predicates:
            - Path=/v1/integration-service/api/**

        - id: chat-client-service
          uri: lb://CHAT-SERVICE
          predicates:
            - Path=/v1/chat-service/api/**


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty: DEBUG