server:
  port: 8000

spring:
  application:
    name: apigateway-service

#  cloud:
#    gateway:
#      routes:
#        - id: integration-service
#          uri: lb://INTEGRATION-SERVICE
#          predicates:
#            - Path=/v1/admin/api/**
#
#        - id: integration-service
#          uri: lb://INTEGRATION-SERVICE
#          predicates:
#            - Path=/v1/api/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty: DEBUG